{% set name = "lipyphilic" %}
{% set version = "0.6.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lipyphilic-{{ version }}.tar.gz
  sha256: 055b6e93e3d4cf7188c8322c772c35c7105910e5649372dc8ac58a6ef31a3a31

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.6
  run:
    - freud >=2.4.1
    - mdanalysis >=1.0
    - tidynamics
    - numpy >=1.16
    - pandas >=1.1
    - python >=3.6
    - scipy
    - tqdm
    - mock # required by MDAnalysis
    - cython # required by gsd and Freud

test:
  imports:
    - lipyphilic
    - lipyphilic.lib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/p-j-smith/lipyphilic
  summary: A Python toolkit for analysing MD simulations of lipid membranes
  license: GPL-2.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - p-j-smith
